project:
  type: website
  output-dir: docs

website:
  cookie-consent: true
  open-graph: true
  title: "Jeffrey Lin"
  navbar:
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/jeffreylin24/
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/epijlin/jeffrey-website
          - text: Report a Bug
            href:  https://bugs.com
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Life"
        href: life.qmd
  page-footer: 
    left: "&copy; Copyright 2024, Jeffrey Lin"
    right: "Built with [Quarto](https://quarto.org/)"
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

body-header: |
  This page brought to you by <https://example.com>

editor: visual

